#!/bin/sh
# Run frontend checks
cd frontend
pnpm format:lint:tsc
FRONTEND_EXIT=$?

# Go back to root directory and run Go tests
cd ..
echo "Running Go tests..."
gotestsum --format=pkgname --format-icons=hivis ./internal/...
GO_EXIT=$?

# Exit with error if either check failed
if [ $FRONTEND_EXIT -ne 0 ] || [ $GO_EXIT -ne 0 ]; then
  exit 1
fi

exit 0
