name: "Setup Frontend"
description: "Checkouts code, sets up Bun, and installs dependencies"
inputs:
  run-knip:
    description: "Run knip dead-code scan after installing dependencies"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install dependencies
      shell: bash
      working-directory: ./frontend
      run: bun install

    - name: Run Knip dead-code scan
      if: ${{ inputs.run-knip == 'true' }}
      shell: bash
      working-directory: ./frontend
      run: bun run knip:ci
