// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class MostRecentNoteResponse {
    "success": boolean;
    "message": string;

    /** Creates a new MostRecentNoteResponse instance. */
    constructor($$source: Partial<MostRecentNoteResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MostRecentNoteResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): MostRecentNoteResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MostRecentNoteResponse($$parsedSource as Partial<MostRecentNoteResponse>);
    }
}
