// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddFolder(folderName: string): Promise<$models.FolderResponse> & { cancel(): void } {
    let $resultPromise = $Call.ByID(556274632, folderName) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function DeleteFolder(folderName: string): Promise<$models.FolderResponse> & { cancel(): void } {
    let $resultPromise = $Call.ByID(562179514, folderName) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetFolders(): Promise<$models.FolderResponse> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3909346760) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * Updates the folder name
 */
export function RenameFolder(oldFolderName: string, newFolderName: string): Promise<$models.FolderResponse> & { cancel(): void } {
    let $resultPromise = $Call.ByID(192921743, oldFolderName, newFolderName) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.FolderResponse.createFrom;
