// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class projectSettingsFrontend {
    "pinnedNotes": string[];

    /** Creates a new projectSettingsFrontend instance. */
    constructor($$source: Partial<projectSettingsFrontend> = {}) {
        if (!("pinnedNotes" in $$source)) {
            this["pinnedNotes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new projectSettingsFrontend instance from a string or object.
     */
    static createFrom($$source: any = {}): projectSettingsFrontend {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pinnedNotes" in $$parsedSource) {
            $$parsedSource["pinnedNotes"] = $$createField0_0($$parsedSource["pinnedNotes"]);
        }
        return new projectSettingsFrontend($$parsedSource as Partial<projectSettingsFrontend>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
