// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CleanAndCopyFiles(filePaths: string, folderPath: string, notePath: string): Promise<string[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3734486965, filePaths, folderPath, notePath) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function RemoveImage(src: string): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3384988374, src) as any;
    return $resultPromise;
}

export function RunCode(language: string, code: string, command: string): Promise<$models.CodeResponse> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1444881027, language, code, command) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function SyncChangesWithRepo(): Promise<$models.GitResponse> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1837210235) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function UploadImage(folder: string, note: string): Promise<$models.UploadImageResponse> & { cancel(): void } {
    let $resultPromise = $Call.ByID(31173221, folder, note) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.CodeResponse.createFrom;
const $$createType2 = $models.GitResponse.createFrom;
const $$createType3 = $models.UploadImageResponse.createFrom;
