// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum favContextKey {
}
export enum key1 {
}
export enum key2 {
}
export enum value {
}
