// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Call} from '@wailsio/runtime';
import {FolderResponse} from './models';

export async function AddFolder(folderName: string) : Promise<FolderResponse> {
	return Call.ByName("main.FolderService.AddFolder", folderName);
}

export async function DeleteFolder(folderName: string) : Promise<FolderResponse> {
	return Call.ByName("main.FolderService.DeleteFolder", folderName);
}

export async function GetFolders() : Promise<FolderResponse> {
	return Call.ByName("main.FolderService.GetFolders");
}

// Updates the folder name
export async function RenameFolder(oldFolderName: string, newFolderName: string) : Promise<FolderResponse> {
	return Call.ByName("main.FolderService.RenameFolder", oldFolderName, newFolderName);
}

