// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Call} from '@wailsio/runtime';
import {GitResponse} from './models';
import {NodeResponse} from './models';
import {UploadImageResponse} from './models';

export async function CleanAndCopyFiles(filePaths: string, folderPath: string, notePath: string) : Promise<string[], void> {
	return Call.ByName("main.NodeService.CleanAndCopyFiles", filePaths, folderPath, notePath);
}

export async function RemoveImage(src: string) : Promise<boolean> {
	return Call.ByName("main.NodeService.RemoveImage", src);
}

export async function RunCode(language: string, code: string, command: string) : Promise<NodeResponse> {
	return Call.ByName("main.NodeService.RunCode", language, code, command);
}

export async function SyncChangesWithRepo() : Promise<GitResponse> {
	return Call.ByName("main.NodeService.SyncChangesWithRepo");
}

export async function UploadImage(folder: string, note: string) : Promise<UploadImageResponse> {
	return Call.ByName("main.NodeService.UploadImage", folder, note);
}

