// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Call} from '@wailsio/runtime';
import {AddFolderResponse} from './models';
import {NoteMarkdownResponse} from './models';
import {NoteResponse} from './models';

export async function AddNoteToFolder(folderName: string, noteTitle: string) : Promise<AddFolderResponse> {
	return Call.ByName("main.NoteService.AddNoteToFolder", folderName, noteTitle);
}

export async function GetAttachments(folderName: string) : Promise<NoteResponse> {
	return Call.ByName("main.NoteService.GetAttachments", folderName);
}

export async function GetNoteMarkdown(folderName: string, noteTitle: string) : Promise<NoteMarkdownResponse> {
	return Call.ByName("main.NoteService.GetNoteMarkdown", folderName, noteTitle);
}

export async function GetNotes(folderName: string) : Promise<NoteResponse> {
	return Call.ByName("main.NoteService.GetNotes", folderName);
}

export async function RenameNote(folderName: string, oldNoteTitle: string, newNoteTitle: string) : Promise<NoteResponse> {
	return Call.ByName("main.NoteService.RenameNote", folderName, oldNoteTitle, newNoteTitle);
}

export async function SetNoteMarkdown(folderName: string, noteTitle: string, markdown: string) : Promise<NoteMarkdownResponse> {
	return Call.ByName("main.NoteService.SetNoteMarkdown", folderName, noteTitle, markdown);
}

export async function ValidateMostRecentNotes(paths: string[]) : Promise<string[]> {
	return Call.ByName("main.NoteService.ValidateMostRecentNotes", paths);
}

