// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class ProjectSettingsJson {
    "pinned_notes": string[];

    /** Creates a new ProjectSettingsJson instance. */
    constructor($$source: Partial<ProjectSettingsJson> = {}) {
        if (!("pinned_notes" in $$source)) {
            this["pinned_notes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectSettingsJson instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectSettingsJson {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pinned_notes" in $$parsedSource) {
            $$parsedSource["pinned_notes"] = $$createField0_0($$parsedSource["pinned_notes"]);
        }
        return new ProjectSettingsJson($$parsedSource as Partial<ProjectSettingsJson>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
