// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project_helpers} from '../models';
import {project_types} from '../models';
import {git_helpers} from '../models';

export function AddFolderUsingName(arg1:string):Promise<project_helpers.FileReturnStruct>;

export function AddNoteToFolder(arg1:string,arg2:string):Promise<project_helpers.FileReturnStruct>;

export function DeleteFolder(arg1:string):Promise<void>;

export function GetFolderNames():Promise<Array<string>>;

export function GetNoteMarkdown(arg1:string,arg2:string):Promise<string>;

export function GetNoteTitles(arg1:string):Promise<Array<string>>;

export function RenameFolder(arg1:string,arg2:string):Promise<void>;

export function RenameNoteTitle(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RunCode(arg1:string,arg2:string,arg3:string):Promise<project_types.SuccessHandler>;

export function SetNoteMarkdown(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SyncChangesWithRepo():Promise<git_helpers.GitReponse>;

export function UploadImagesToFolder(arg1:string,arg2:string):Promise<Array<string>>;
