// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StoreMarkdown(arg1:string):Promise<void>;

export function WriteNote(arg1:string,arg2:string):Promise<boolean>;
