// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project_helpers} from '../models';

export function AddFolderUsingName(arg1:string):Promise<project_helpers.AddFolderRequest>;

export function GetFolderNames():Promise<Array<string>>;

export function WriteNote(arg1:string,arg2:string):Promise<boolean>;
