// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolderUsingName(arg1) {
  return window['go']['main']['App']['AddFolderUsingName'](arg1);
}

export function AddNoteToFolder(arg1, arg2) {
  return window['go']['main']['App']['AddNoteToFolder'](arg1, arg2);
}

export function GetFolderNames() {
  return window['go']['main']['App']['GetFolderNames']();
}

export function GetNoteMarkdown(arg1, arg2) {
  return window['go']['main']['App']['GetNoteMarkdown'](arg1, arg2);
}

export function GetNoteTitles(arg1) {
  return window['go']['main']['App']['GetNoteTitles'](arg1);
}

export function SetNoteMarkdown(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetNoteMarkdown'](arg1, arg2, arg3);
}

export function WriteNote(arg1, arg2) {
  return window['go']['main']['App']['WriteNote'](arg1, arg2);
}
