name: 💨 Go Unit Tests
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches: [master]
    paths-ignore:
      - '**.md'

jobs:
  go-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 🔀 Checking out Repo
        uses: actions/checkout@v4

      - name: 📦 Setting up go
        uses: actions/setup-go@v5
        with: 
          go-version: '1.21.6'
      
      - name: ⬇️ Install dependencies
        run: go mod tidy

      - name: 🧪 Run tests
        run: |
          ls
          make test
        